version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - appreservas
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash_springboot
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      RABBIT_MQ_IP: "rabbitmq"
    networks:
      - appreservas
    depends_on:
      - rabbitmq
  auth-backend: 
    build: 
      context: ./auth
    ports: 
      - '8085:8085'
    environment:
      - LOGSTASH_URL=logstash:5000
      - RABBIT_MQ_IP=rabbitmq
    depends_on:
      - logstash
      - rabbitmq
    networks:
      - appreservas
  reservas-backend: 
    build: 
      context: ./appreservas
    ports: 
      - '8095:8095'
    environment:
      - LOGSTASH_URL=logstash:5000
      - RABBIT_MQ_IP=rabbitmq
    depends_on:
      - logstash
      - rabbitmq
    networks:
      - appreservas
networks:
  appreservas:

