apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
          name: logstash
          ports:
          - containerPort: 25826
          - containerPort: 5044
          env:
          - name: RABBIT_MQ_IP
            value: "rabbitmq.default.svc.cluster.local"
          resources: {}
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/
            - name: pipeline-volume
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: config-volume
          configMap:
            name: logstash-config
        - name: pipeline-volume
          configMap:
            name: logstash-pipeline
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  selector:
    app: logstash
  ports:
    - name: logstash
      port: 5044
      targetPort: logstash
  type: LoadBalancer